### ISSUE TITLE
Some errors related to np.asarray

### ISSUE THREAD

**Issue by Cubism-star** [artberryx/LSD#1]
In many places in the code (e.g., iod.py), np.asarray() is used to convert tensors to arrays. But this will cause an error when the tensor is on cuda device. If we just use .cpu() to transfer the tensors to cpu, it will cause errors in other codes.  

Is the code itself only able to run with cpu?

**Comment by Cubism-star** [comment]
maybe this issue could be solved by change np.asarray("list()") to torch.stack("list()")

**Comment by seohongpark** [comment]
This happens when you use a newer version of `numpy`.
To resolve this issue, you can modify the code like this:
```
def to_np_object_arr(x):
    arr = np.empty(len(x), dtype=np.object)
    for i, t in enumerate(x):
        arr[i] = t
    return arr

...

obs = to_np_object_arr(
            [_to_torch_float32(path['observations'][:self._cur_max_path_length])
             for path in paths])
```
