### ISSUE TITLE
About the constraint term in the objective function J^{LSD}

### ISSUE THREAD

**Issue by gaiyi7788** [artberryx/LSD#4]
Thank you for your interesting work!

I wonder if the constraint term in the objective function J^{LSD} of the optimization φ is considered in the code implementation? And why is there no constraint term in equation (7)?

Looking forward to your reply!

**Comment by seohongpark** [comment]
Hi Pengyu, thank you for your interest in the work. As mentioned in Section 3 and Appendix C, we implement the Lipschitz constraint in Eq (6) by using Spectral Normalization (`--spectral_normalization=1`).  We do impose the same constraint for the per-transition reward in Eq (7) as well, but we didn't explicitly write this constraint in Eq (7) again for simplicity.
