### ISSUE TITLE
Correlation matrix

### ISSUE THREAD

**Issue by 21yrm** [artberryx/LSD#6]
The experimental section of the LSD paper mentions a Correlation matrix, but it is not involved in the code. Could you please explain how this Correlation matrix is obtained?

**Comment by seohongpark** [comment]
Hi 21yrm, the correlation matrix was computed by `np.corrcoef` between $\phi(s)$ and $s$.

**Comment by 21yrm** [comment]
During the eval stage, sample 48 z, each z samples 2 trajectories, so is the correlation matrix calculated for all z and all trajectories, or is a correlation matrix calculated for each z and its corresponding trajectories?

**Comment by seohongpark** [comment]
It is computed from all $z$s and all states, but we used more than 96 trajectories to produce the qualitative results in the paper.

**Comment by 21yrm** [comment]
Okay, I think I understand roughly. Thank you.
